In [12]:
import pandas as pd

In [23]:
df = pd.read_csv("clean_data.csv")

df

,Unnamed: 0,amount_paid_usd,tags,country,title,artist,at
0,0,55,Punk,Germany,In the Name of Love,Die angepissten Turnbeutel,"01/03/2024, 15:22:01"
1,1,63,Alternative,Italy,Amras - Infinite_Connection,Electricmoonrecords,"01/03/2024, 15:22:02"
2,1,63,Psychedelic,Italy,Amras - Infinite_Connection,Electricmoonrecords,"01/03/2024, 15:22:02"
3,2,63,Alternative,Italy,Gotalien - Weed Out Sense,Electricmoonrecords,"01/03/2024, 15:22:02"
4,2,63,Psychedelic,Italy,Gotalien - Weed Out Sense,Electricmoonrecords,"01/03/2024, 15:22:02"
...,...,...,...,...,...,...,...
335,64,189,Tekno,United Kingdom,Startle Easy,Gullyteen,"01/03/2024, 15:23:57"
336,64,189,Jungle,United Kingdom,Startle Easy,Gullyteen,"01/03/2024, 15:23:57"
337,64,189,DNB,United Kingdom,Startle Easy,Gullyteen,"01/03/2024, 15:23:57"
338,64,189,Electronic,United Kingdom,Startle Easy,Gullyteen,"01/03/2024, 15:23:57"
339,64,189,Breakcore,United Kingdom,Startle Easy,Gullyteen,"01/03/2024, 15:23:57"